name: Repository Dispatch Workflow

# Triggered by the repository_dispatch event
on:
  repository_dispatch:
    types: [hello_event] # Custom event type

permissions:
  contents: write

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    
        
      - name: Respond to Repository Dispatch
        run: echo "Hello,${{ github.event.client_payload.name }}!"

      - name: Create JSON file from payload
        run: |
          echo '${{ toJSON(github.event.client_payload) }}' > payload_data.json
          
      - name: Commit and push
        run: |
          git config user.email "suriyaramesh486@gmail.com"
          git config user.name "rameshkrishnan03"
          git add payload_data.json
          git commit -m "Save client payload data"
          git push origin main
