name: Repository Dispatch Workflow

# Triggered by the repository_dispatch event
on:
  repository_dispatch:
    types: [hello_event] # Custom event type

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Respond to Repository Dispatch
        run: echo "Hello,${{ github.event.client_payload.name }}!"

      - name: Create JSON file from payload
        run: |
          echo '${{ toJSON(github.event.client_payload) }}' > payload_data.json
          
      - name: Commit and push
        run: |
          git config --global user.name 'rameshkrishnan03'
          git config --global user.email 'suriyaramesh486@gmail.com'
          git add payload_data.json
          git commit -m "Save client payload data"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
  permissions:
  contents: write
