name: Upload Encryption Workflow to New Repo

on:
  repository_dispatch:
    types: [upload-workflow]
    inputs:
      repo_name:
        description: 'Name of the new repository'
        required: true
jobs:
  upload-workflow:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.event.client_payload.token }}
      NEW_REPO_NAME: ${{ github.event.client_payload.repo_name }}
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Clone the new repository
      run: |
        git clone https://github.com/${{ github.event.client_payload.name }}/${NEW_REPO_NAME}.git
        cd $NEW_REPO_NAME
        mkdir -p .github/workflows

    - name: Copy Encryption.yml to the new repository
      run: |
        cp .github/workflows/Create_secret.yml "${NEW_REPO_NAME}/.github/workflows/"

    - name: Commit and push workflow to the new repository
      run: |
        cd $NEW_REPO_NAME
        git config user.email "suriyaramesh486@gmail.com"
        git config user.name "rameshkrishnan03"
        git add .
        git commit -m "Add Encryption workflow"
        git push origin main
